version: "2"
run:
    tests: true
    concurrency: 4
    # timeout: 5m

linters:
    exclusions:
        paths:
            - tests/
    default: all
    disable:
        - wsl
        - wsl_v5
        - depguard
        - exhaustruct
        - paralleltest
        - testpackage
        - wrapcheck
        - nlreturn
        - ireturn
        - nosprintfhostport
        - tagliatelle
        - revive
        - tagalign
        - varnamelen
    enable:
        - errcheck
        - unparam
        - dupl
        - misspell
        - gocyclo
        - goconst
        - godot
        - gosec
        - ineffassign
        - unconvert
        - copyloopvar
        - bodyclose
        - prealloc
        - nakedret
        - noctx
        - forbidigo
        - asasalint
        - unused
        - lll
        - nolintlint
        - rowserrcheck
        - sqlclosecheck
        - wastedassign
        - errorlint
        - makezero
        - containedctx
        - dogsled
        - funlen
        - goheader

    settings:
        funlen:
            lines: 80
            statements: 80

issues:
    max-issues-per-linter: 0
    max-same-issues: 0
