// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avitotech-pr-reviewer/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetByID(ctx context.Context, teamID string) (*domain.Team, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Team, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Team); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTeamRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockTeamRepository_Expecter) GetByID(ctx interface{}, teamID interface{}) *MockTeamRepository_GetByID_Call {
	return &MockTeamRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, teamID)}
}

func (_c *MockTeamRepository_GetByID_Call) Run(run func(ctx context.Context, teamID string)) *MockTeamRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) Return(team *domain.Team, err error) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, teamID string) (*domain.Team, error)) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
