// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avitotech-pr-reviewer/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPrRepository creates a new instance of MockPrRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrRepository {
	mock := &MockPrRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrRepository is an autogenerated mock type for the PrRepository type
type MockPrRepository struct {
	mock.Mock
}

type MockPrRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrRepository) EXPECT() *MockPrRepository_Expecter {
	return &MockPrRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPrRepository
func (_mock *MockPrRepository) Create(ctx context.Context, pr *domain.PullRequest) (*domain.PullRequest, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PullRequest) (*domain.PullRequest, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PullRequest) *domain.PullRequest); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.PullRequest) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPrRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *domain.PullRequest
func (_e *MockPrRepository_Expecter) Create(ctx interface{}, pr interface{}) *MockPrRepository_Create_Call {
	return &MockPrRepository_Create_Call{Call: _e.mock.On("Create", ctx, pr)}
}

func (_c *MockPrRepository_Create_Call) Run(run func(ctx context.Context, pr *domain.PullRequest)) *MockPrRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.PullRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrRepository_Create_Call) Return(pullRequest *domain.PullRequest, err error) *MockPrRepository_Create_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPrRepository_Create_Call) RunAndReturn(run func(ctx context.Context, pr *domain.PullRequest) (*domain.PullRequest, error)) *MockPrRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockPrRepository
func (_mock *MockPrRepository) GetByID(ctx context.Context, prID string) (*domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPrRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPrRepository_Expecter) GetByID(ctx interface{}, prID interface{}) *MockPrRepository_GetByID_Call {
	return &MockPrRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, prID)}
}

func (_c *MockPrRepository_GetByID_Call) Run(run func(ctx context.Context, prID string)) *MockPrRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrRepository_GetByID_Call) Return(pullRequest *domain.PullRequest, err error) *MockPrRepository_GetByID_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPrRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, prID string) (*domain.PullRequest, error)) *MockPrRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewerIDs provides a mock function for the type MockPrRepository
func (_mock *MockPrRepository) GetReviewerIDs(ctx context.Context, prID string) ([]string, error) {
	ret := _mock.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewerIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, prID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrRepository_GetReviewerIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewerIDs'
type MockPrRepository_GetReviewerIDs_Call struct {
	*mock.Call
}

// GetReviewerIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPrRepository_Expecter) GetReviewerIDs(ctx interface{}, prID interface{}) *MockPrRepository_GetReviewerIDs_Call {
	return &MockPrRepository_GetReviewerIDs_Call{Call: _e.mock.On("GetReviewerIDs", ctx, prID)}
}

func (_c *MockPrRepository_GetReviewerIDs_Call) Run(run func(ctx context.Context, prID string)) *MockPrRepository_GetReviewerIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrRepository_GetReviewerIDs_Call) Return(strings []string, err error) *MockPrRepository_GetReviewerIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockPrRepository_GetReviewerIDs_Call) RunAndReturn(run func(ctx context.Context, prID string) ([]string, error)) *MockPrRepository_GetReviewerIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SetMerged provides a mock function for the type MockPrRepository
func (_mock *MockPrRepository) SetMerged(ctx context.Context, prID string) (*domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for SetMerged")
	}

	var r0 *domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrRepository_SetMerged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMerged'
type MockPrRepository_SetMerged_Call struct {
	*mock.Call
}

// SetMerged is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPrRepository_Expecter) SetMerged(ctx interface{}, prID interface{}) *MockPrRepository_SetMerged_Call {
	return &MockPrRepository_SetMerged_Call{Call: _e.mock.On("SetMerged", ctx, prID)}
}

func (_c *MockPrRepository_SetMerged_Call) Run(run func(ctx context.Context, prID string)) *MockPrRepository_SetMerged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrRepository_SetMerged_Call) Return(pullRequest *domain.PullRequest, err error) *MockPrRepository_SetMerged_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPrRepository_SetMerged_Call) RunAndReturn(run func(ctx context.Context, prID string) (*domain.PullRequest, error)) *MockPrRepository_SetMerged_Call {
	_c.Call.Return(run)
	return _c
}

// SetNewReviewer provides a mock function for the type MockPrRepository
func (_mock *MockPrRepository) SetNewReviewer(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) (*domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID, oldReviewerID, newReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for SetNewReviewer")
	}

	var r0 *domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrRepository_SetNewReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNewReviewer'
type MockPrRepository_SetNewReviewer_Call struct {
	*mock.Call
}

// SetNewReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldReviewerID string
//   - newReviewerID string
func (_e *MockPrRepository_Expecter) SetNewReviewer(ctx interface{}, prID interface{}, oldReviewerID interface{}, newReviewerID interface{}) *MockPrRepository_SetNewReviewer_Call {
	return &MockPrRepository_SetNewReviewer_Call{Call: _e.mock.On("SetNewReviewer", ctx, prID, oldReviewerID, newReviewerID)}
}

func (_c *MockPrRepository_SetNewReviewer_Call) Run(run func(ctx context.Context, prID string, oldReviewerID string, newReviewerID string)) *MockPrRepository_SetNewReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPrRepository_SetNewReviewer_Call) Return(pullRequest *domain.PullRequest, err error) *MockPrRepository_SetNewReviewer_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPrRepository_SetNewReviewer_Call) RunAndReturn(run func(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) (*domain.PullRequest, error)) *MockPrRepository_SetNewReviewer_Call {
	_c.Call.Return(run)
	return _c
}
