// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avitotech-pr-reviewer/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// CreateWithMembers provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) CreateWithMembers(ctx context.Context, teamName string, members []domain.Member) (*domain.Team, error) {
	ret := _mock.Called(ctx, teamName, members)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithMembers")
	}

	var r0 *domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []domain.Member) (*domain.Team, error)); ok {
		return returnFunc(ctx, teamName, members)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []domain.Member) *domain.Team); ok {
		r0 = returnFunc(ctx, teamName, members)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []domain.Member) error); ok {
		r1 = returnFunc(ctx, teamName, members)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_CreateWithMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithMembers'
type MockTeamRepository_CreateWithMembers_Call struct {
	*mock.Call
}

// CreateWithMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - members []domain.Member
func (_e *MockTeamRepository_Expecter) CreateWithMembers(ctx interface{}, teamName interface{}, members interface{}) *MockTeamRepository_CreateWithMembers_Call {
	return &MockTeamRepository_CreateWithMembers_Call{Call: _e.mock.On("CreateWithMembers", ctx, teamName, members)}
}

func (_c *MockTeamRepository_CreateWithMembers_Call) Run(run func(ctx context.Context, teamName string, members []domain.Member)) *MockTeamRepository_CreateWithMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []domain.Member
		if args[2] != nil {
			arg2 = args[2].([]domain.Member)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamRepository_CreateWithMembers_Call) Return(team *domain.Team, err error) *MockTeamRepository_CreateWithMembers_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepository_CreateWithMembers_Call) RunAndReturn(run func(ctx context.Context, teamName string, members []domain.Member) (*domain.Team, error)) *MockTeamRepository_CreateWithMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetByName(ctx context.Context, teamName string) (*domain.Team, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Team, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Team); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTeamRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTeamRepository_Expecter) GetByName(ctx interface{}, teamName interface{}) *MockTeamRepository_GetByName_Call {
	return &MockTeamRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, teamName)}
}

func (_c *MockTeamRepository_GetByName_Call) Run(run func(ctx context.Context, teamName string)) *MockTeamRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetByName_Call) Return(team *domain.Team, err error) *MockTeamRepository_GetByName_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, teamName string) (*domain.Team, error)) *MockTeamRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}
