// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avitotech-pr-reviewer/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// ListByTeamID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ListByTeamID(ctx context.Context, teamID string) ([]domain.User, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTeamID")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.User, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.User); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_ListByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTeamID'
type MockUserRepository_ListByTeamID_Call struct {
	*mock.Call
}

// ListByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockUserRepository_Expecter) ListByTeamID(ctx interface{}, teamID interface{}) *MockUserRepository_ListByTeamID_Call {
	return &MockUserRepository_ListByTeamID_Call{Call: _e.mock.On("ListByTeamID", ctx, teamID)}
}

func (_c *MockUserRepository_ListByTeamID_Call) Run(run func(ctx context.Context, teamID string)) *MockUserRepository_ListByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_ListByTeamID_Call) Return(users []domain.User, err error) *MockUserRepository_ListByTeamID_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_ListByTeamID_Call) RunAndReturn(run func(ctx context.Context, teamID string) ([]domain.User, error)) *MockUserRepository_ListByTeamID_Call {
	_c.Call.Return(run)
	return _c
}
